#!/bin/bash
set -e

case "$1" in
configure|triggered)
    if [ -d /run/systemd/system ]; then
        mkdir -p /etc/systemd/system/local-fs.target.wants
        ln -sf /usr/lib/systemd/system/ostree-remount.service \
            /etc/systemd/system/local-fs.target.wants/ostree-remount.service
    fi
    ;;
esac