name: Build & Publish Bootc .deb

on:
  workflow_dispatch:
  # à la main uniquement, tu rebuildes quand tu veux

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:trixie

    steps:
      - name: Install build deps
        shell: bash
        run: |
          apt update
          apt install -y \
            ca-certificates \
            openssl
          sed -i "s|http://|https://|g" /etc/apt/sources.list.d/debian.sources
          apt update
          apt install -y \
            git \
            curl \
            wget \
            nodejs \
            npm \
            make \
            build-essential \
            go-md2man \
            libzstd-dev \
            pkgconf \
            autoconf \
            automake \
            libtool \
            libglib2.0-dev \
            libcurl4-openssl-dev \
            libgpgme-dev \
            libarchive-dev \
            libmount-dev \
            libfuse3-dev \
            libssl-dev \
            libsystemd-dev \
            gobject-introspection \
            libgirepository1.0-dev \
            libsoup-3.0-dev \
            bison

      - name: Checkout
        uses: actions/checkout@v7 
        with:
          submodules: recursive
      
      - name: Prepare environement
        shell: bash
        run: |
          cp -r ./workflows/bootc-debs-builder/preinstall/* /

      - name: Build ostree
        shell: bash
        env:
          CARGO_HOME: "/build/rust"
          RUSTUP_HOME: "/build/rust"
          OSTREE_VER: "2026.1"
        run: |
          mkdir -p /{build,debs}
          
          curl -fsSL \
            https://github.com/ostreedev/ostree/releases/download/v${OSTREE_VER}/libostree-${OSTREE_VER}.tar.xz \
            | tar -xJ -C /build
          cd /build/libostree-${OSTREE_VER}

          ./configure --prefix=/usr --sysconfdir=/etc \
            --disable-gtk-doc --disable-man
          
          make -j$(nproc)
          make -j$(nproc) install DESTDIR=/output/ostree

          dpkg-shlibdeps -O $(find . -name "libostree-1.so*" ! -name "*.la" | head -1) \
            2>/dev/null | sed 's/shlibs:Depends=//' > /tmp/ostree-deps
          DEPS=$(cat /tmp/ostree-deps)

          sed -i \
            -e "s|{{ VER }}|${OSTREE_VER}|g" \
            -e "s|{{ DEPS }}|${DEPS}|g" \
            /output/ostree/DEBIAN/control
          cp -r ./workflows/bootc-debs-builder/ostreepostinstall/* /output/ostree/
          
          dpkg-deb --build /output/ostree /debs/libostree_${OSTREE_VER}_amd64.deb
          apt install -y /debs/libostree_${OSTREE_VER}_amd64.deb

      - name: Build bootc
        shell: bash
        env:
          CARGO_HOME: "/build/rust"
          RUSTUP_HOME: "/build/rust"
          BOOTC_VER: "v1.16.1"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
            | sh -s -- --profile minimal -y
          
          git clone --depth=1 --branch "${BOOTC_VER}" \
            https://github.com/bootc-dev/bootc.git /build/bootc
          
          curl -fsSL \
            https://github.com/bootc-dev/bootc/releases/download/${BOOTC_VER}/bootc-${BOOTC_VER#v}-vendor.tar.zstd \
            | tar --zstd -x -C /build/bootc
          
          . ${RUSTUP_HOME}/env
          cargo build --release --manifest-path /build/bootc/Cargo.toml

          make -j$(nproc) -C /build/bootc manpages DESTDIR=/output/bootc
          make -C /build/bootc install-all DESTDIR=/output/bootc

          dpkg-shlibdeps -O /build/bootc/target/release/bootc \
            2>/dev/null | sed 's/shlibs:Depends=//' > /tmp/bootc-deps
          DEPS=$(cat /tmp/bootc-deps)

          sed -i \
            -e "s|{{ VER }}|${BOOTC_VER#v}|g" \
            -e "s|{{ DEPS }}|${DEPS}|g"  \
            /output/bootc/DEBIAN/control
          cp -r ./workflows/bootc-debs-builder/bootcpostinstall/* /output/bootc/
          
          dpkg-deb --build /output/bootc /debs/bootc_${BOOTC_VER#v}_amd64.deb

      - name: Create APT repo
        id: create-apt-repo
        uses: morph027/apt-repo-action@v3
        with:
          repo-name: debian-bootc
          signing-key: ${{ secrets.APT_GPG_KEY }}
          codename: trixie
          components: main
          architectures: amd64

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.create-apt-repo.outputs.dir }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4